En la siguiente URL puedes encontrar varios archivos XLS libres.

https://file-examples.com/index.php/sample-documents-download/sample-xls-download/

Para esta práctica debes descargar los dos archivos que contienen 5000 filas.

Para tu mayor comodidad, estos archivos ya han sido descargados y ya están preparados en esta carpeta

1. El primer paso es abrir cada uno de ellos y cargarlos en su propio DataFrame. Recuerda que debes montar tu unidad de GoogleDrive para poder tener acceso a los archivos

In [19]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
dataframe1 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Data Science and AI/Tercera sesión/Ejemplo1.xls')
dataframe2 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Data Science and AI/Tercera sesión/Ejemplo2.xlsx')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

2. El siguiente paso, es verificar que han sido cargados exitosamente

In [20]:
dataframe1

,Unnamed: 0,First Name,Last Name,Gender,Country,Age,Date,Id
0,1,Dulce,Abril,Female,United States,32,15/10/2017,1562
1,2,Mara,Hashimoto,Female,Great Britain,25,16/08/2016,1582
2,3,Philip,Gent,Male,France,36,21/05/2015,2587
3,4,Kathleen,Hanner,Female,United States,25,15/10/2017,3549
4,5,Nereida,Magwood,Female,United States,58,16/08/2016,2468
...,...,...,...,...,...,...,...,...
4995,4996,Roma,Lafollette,Female,United States,34,15/10/2017,2654
4996,4997,Felisa,Cail,Female,United States,28,16/08/2016,6525
4997,4998,Demetria,Abbey,Female,United States,32,21/05/2015,3265
4998,4999,Jeromy,Danz,Male,United States,39,15/10/2017,3265
4999,5000,Rasheeda,Alkire,Female,United States,29,16/08/2016,6125

In [21]:
dataframe2

,Unnamed: 0,First Name,Last Name,Gender,Country,Age,Date,Id
0,1,Dulce,Abril,Female,United States,32,15/10/2017,1562
1,2,Mara,Hashimoto,Female,Great Britain,25,16/08/2016,1582
2,3,Philip,Gent,Male,France,36,21/05/2015,2587
3,4,Kathleen,Hanner,Female,United States,25,15/10/2017,3549
4,5,Nereida,Magwood,Female,United States,58,16/08/2016,2468
...,...,...,...,...,...,...,...,...
4995,4996,Roma,Lafollette,Female,United States,34,15/10/2017,2654
4996,4997,Felisa,Cail,Female,United States,28,16/08/2016,6525
4997,4998,Demetria,Abbey,Female,United States,32,21/05/2015,3265
4998,4999,Jeromy,Danz,Male,United States,39,15/10/2017,3265
4999,5000,Rasheeda,Alkire,Female,United States,29,16/08/2016,6125

3. El siguiente paso, a manera de repaso, es para cada uno de los dos DataFrames, encontrar el número de personas que son originarios de los Estados Unidos (United States) tanto para el primer archivo, como para el segundo.

In [22]:
dataframe1USA = dataframe1[dataframe1['Country'] == 'United States']
print(f"La cantidad de personas estadounidenses en el primer registro es de: {dataframe1USA['Country'].count()}")
dataframe2USA = dataframe2[dataframe2['Country'] == 'United States']
print(f"La cantidad de personas estadounidenses en el segundo registro es de: {dataframe2USA['Country'].count()}")

La cantidad de personas estadounidenses en el primer registro es de: 2400
La cantidad de personas estadounidenses en el segundo registro es de: 2400